# A small, representative subset of java.lang and java.util classes that
# appear very often in real code. Listing all of the JRE is unnecessary and
# would bloat the popup; plugins that want deeper JRE coverage can extend
# this list (or plug a symbol extractor reading a local Javadoc index).
#
# Each entry is a (name, signature_or_None) pair.

LANG_PATTERNS = ["java", ".java"]

BUILTIN_SYMBOLS = [
    # --- java.lang classes --------------------------------------------------
    ("String", "final class String implements CharSequence, Comparable<String>"),
    ("Integer", "final class Integer extends Number implements Comparable<Integer>"),
    ("Long", "final class Long extends Number implements Comparable<Long>"),
    ("Double", "final class Double extends Number implements Comparable<Double>"),
    ("Float", "final class Float extends Number implements Comparable<Float>"),
    ("Boolean", "final class Boolean implements Serializable, Comparable<Boolean>"),
    ("Character", "final class Character implements Serializable, Comparable<Character>"),
    ("Byte", "final class Byte extends Number implements Comparable<Byte>"),
    ("Short", "final class Short extends Number implements Comparable<Short>"),
    ("Object", "class Object"),
    ("Class", "final class Class<T> implements Serializable, GenericDeclaration"),
    ("System", "final class System"),
    ("Math", "final class Math"),
    ("Thread", "class Thread implements Runnable"),
    ("Runnable", "interface Runnable"),
    ("Throwable", "class Throwable implements Serializable"),
    ("Exception", "class Exception extends Throwable"),
    ("RuntimeException", "class RuntimeException extends Exception"),
    ("Error", "class Error extends Throwable"),
    ("Enum", "abstract class Enum<E extends Enum<E>>"),
    ("Iterable", "interface Iterable<T>"),
    ("Comparable", "interface Comparable<T>"),
    ("CharSequence", "interface CharSequence"),
    ("Cloneable", "interface Cloneable"),
    ("Serializable", "interface Serializable"),
    ("AutoCloseable", "interface AutoCloseable"),
    ("Override", "@interface Override"),
    ("Deprecated", "@interface Deprecated"),
    ("SuppressWarnings", "@interface SuppressWarnings"),
    ("SafeVarargs", "@interface SafeVarargs"),
    ("FunctionalInterface", "@interface FunctionalInterface"),
    ("Record", "abstract class Record"),
    ("NullPointerException", "class NullPointerException"),
    ("IllegalArgumentException", "class IllegalArgumentException"),
    ("IllegalStateException", "class IllegalStateException"),
    ("IndexOutOfBoundsException", "class IndexOutOfBoundsException"),
    ("NoSuchElementException", "class NoSuchElementException"),
    ("UnsupportedOperationException", "class UnsupportedOperationException"),

    # --- java.util classes --------------------------------------------------
    ("List", "interface List<E> extends Collection<E>"),
    ("Set", "interface Set<E> extends Collection<E>"),
    ("Map", "interface Map<K, V>"),
    ("Collection", "interface Collection<E> extends Iterable<E>"),
    ("ArrayList", "class ArrayList<E> implements List<E>"),
    ("LinkedList", "class LinkedList<E> implements List<E>, Deque<E>"),
    ("HashSet", "class HashSet<E> implements Set<E>"),
    ("LinkedHashSet", "class LinkedHashSet<E> extends HashSet<E> implements Set<E>"),
    ("TreeSet", "class TreeSet<E> implements NavigableSet<E>"),
    ("HashMap", "class HashMap<K, V> implements Map<K, V>"),
    ("LinkedHashMap", "class LinkedHashMap<K, V> extends HashMap<K, V>"),
    ("TreeMap", "class TreeMap<K, V> implements NavigableMap<K, V>"),
    ("ConcurrentHashMap", "class ConcurrentHashMap<K, V> implements ConcurrentMap<K, V>"),
    ("Optional", "final class Optional<T>"),
    ("OptionalInt", "final class OptionalInt"),
    ("OptionalLong", "final class OptionalLong"),
    ("OptionalDouble", "final class OptionalDouble"),
    ("Stream", "interface Stream<T> extends BaseStream<T, Stream<T>>"),
    ("IntStream", "interface IntStream extends BaseStream<Integer, IntStream>"),
    ("LongStream", "interface LongStream extends BaseStream<Long, LongStream>"),
    ("DoubleStream", "interface DoubleStream extends BaseStream<Double, DoubleStream>"),
    ("Arrays", "class Arrays"),
    ("Collections", "class Collections"),
    ("Objects", "class Objects"),
    ("Iterator", "interface Iterator<E>"),
    ("ListIterator", "interface ListIterator<E> extends Iterator<E>"),
    ("Deque", "interface Deque<E> extends Queue<E>"),
    ("Queue", "interface Queue<E> extends Collection<E>"),
    ("Stack", "class Stack<E> extends Vector<E>"),
    ("Vector", "class Vector<E> implements List<E>"),
    ("Properties", "class Properties extends Hashtable<Object, Object>"),
    ("Date", "class Date implements Serializable, Cloneable, Comparable<Date>"),
    ("Calendar", "abstract class Calendar"),
    ("Random", "class Random"),
    ("UUID", "final class UUID implements Serializable, Comparable<UUID>"),
    ("Locale", "final class Locale implements Cloneable, Serializable"),
    ("Formatter", "class Formatter implements Closeable, Flushable"),
    ("Scanner", "final class Scanner implements Iterator<String>, Closeable"),

    # --- java.util.function -------------------------------------------------
    ("Function", "interface Function<T, R>"),
    ("BiFunction", "interface BiFunction<T, U, R>"),
    ("Predicate", "interface Predicate<T>"),
    ("BiPredicate", "interface BiPredicate<T, U>"),
    ("Consumer", "interface Consumer<T>"),
    ("BiConsumer", "interface BiConsumer<T, U>"),
    ("Supplier", "interface Supplier<T>"),
    ("UnaryOperator", "interface UnaryOperator<T> extends Function<T, T>"),
    ("BinaryOperator", "interface BinaryOperator<T> extends BiFunction<T, T, T>"),

    # --- java.io / java.nio.charset ----------------------------------------
    ("IOException", "class IOException extends Exception"),
    ("FileNotFoundException", "class FileNotFoundException extends IOException"),
    ("File", "class File implements Serializable, Comparable<File>"),
    ("InputStream", "abstract class InputStream implements Closeable"),
    ("OutputStream", "abstract class OutputStream implements Closeable, Flushable"),
    ("Reader", "abstract class Reader implements Readable, Closeable"),
    ("Writer", "abstract class Writer implements Appendable, Closeable, Flushable"),
    ("FileReader", "class FileReader extends InputStreamReader"),
    ("FileWriter", "class FileWriter extends OutputStreamWriter"),
    ("BufferedReader", "class BufferedReader extends Reader"),
    ("BufferedWriter", "class BufferedWriter extends Writer"),
    ("PrintWriter", "class PrintWriter extends Writer"),
    ("PrintStream", "class PrintStream extends FilterOutputStream"),
    ("Serializable", "interface Serializable"),
    ("StandardCharsets", "final class StandardCharsets"),

    # --- java.nio.file ------------------------------------------------------
    ("Path", "interface Path"),
    ("Paths", "class Paths"),
    ("Files", "final class Files"),
    ("FileSystems", "final class FileSystems"),

    # --- java.time ----------------------------------------------------------
    ("Instant", "final class Instant implements Temporal, Comparable<Instant>"),
    ("LocalDate", "final class LocalDate implements ChronoLocalDate"),
    ("LocalTime", "final class LocalTime implements ChronoLocalTime"),
    ("LocalDateTime", "final class LocalDateTime implements ChronoLocalDateTime<LocalDate>"),
    ("ZonedDateTime", "final class ZonedDateTime implements ChronoZonedDateTime<LocalDate>"),
    ("OffsetDateTime", "final class OffsetDateTime implements OffsetDateTimeTemporal"),
    ("Period", "final class Period implements ChronoPeriod"),
    ("Duration", "final class Duration implements TemporalAmount"),
    ("ZoneId", "abstract class ZoneId implements Serializable"),
    ("ZoneOffset", "final class ZoneOffset extends ZoneId"),
    ("Clock", "abstract class Clock"),
    ("DayOfWeek", "enum DayOfWeek"),
    ("Month", "enum Month"),

    # --- java.util.concurrent ----------------------------------------------
    ("Executor", "interface Executor"),
    ("ExecutorService", "interface ExecutorService extends Executor"),
    ("ScheduledExecutorService", "interface ScheduledExecutorService extends ExecutorService"),
    ("Executors", "class Executors"),
    ("Future", "interface Future<V>"),
    ("CompletableFuture", "class CompletableFuture<T> implements Future<T>, CompletionStage<T>"),
    ("Callable", "interface Callable<V>"),
    ("AtomicInteger", "class AtomicInteger extends Number implements Serializable"),
    ("AtomicLong", "class AtomicLong extends Number implements Serializable"),
    ("AtomicBoolean", "class AtomicBoolean implements Serializable"),
    ("AtomicReference", "class AtomicReference<V> implements Serializable"),
    ("CountDownLatch", "class CountDownLatch"),
    ("Semaphore", "class Semaphore"),
    ("ReentrantLock", "class ReentrantLock implements Lock"),
    ("ReentrantReadWriteLock", "class ReentrantReadWriteLock implements ReadWriteLock"),
    ("ConcurrentHashMap", "class ConcurrentHashMap<K, V>"),
    ("BlockingQueue", "interface BlockingQueue<E> extends Queue<E>"),
    ("ArrayBlockingQueue", "class ArrayBlockingQueue<E> extends AbstractQueue<E> implements BlockingQueue<E>"),
    ("LinkedBlockingQueue", "class LinkedBlockingQueue<E> extends AbstractQueue<E> implements BlockingQueue<E>"),
    ("ThreadPoolExecutor", "class ThreadPoolExecutor extends AbstractExecutorService"),

    # --- Common APIs --------------------------------------------------------
    ("StringBuilder", "final class StringBuilder implements CharSequence, Appendable"),
    ("StringBuffer", "class StringBuffer implements CharSequence, Appendable"),
    ("Pattern", "final class Pattern implements Serializable"),
    ("Matcher", "final class Matcher implements MatchResult"),
    ("Comparator", "interface Comparator<T>"),
    ("Consumer", "interface Consumer<T>"),
    ("NoClassDefFoundError", "class NoClassDefFoundError"),
    ("ClassCastException", "class ClassCastException"),
    ("ArithmeticException", "class ArithmeticException"),
    ("ArrayIndexOutOfBoundsException", "class ArrayIndexOutOfBoundsException"),
]
